name: Run get_data_2 Script

on:
  schedule:
  
    # - cron: '0/5 * * * *'  # Runs every 5 days at midnight
    - cron: '0 12 * * *'  # Runs every 5 days at midnight



jobs:
  run_profits_script_and_save_output:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pymongo matplotlib pandas
          
      - name: Run make pdf and save to MongoDB
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
        run: |
          python get_pdf_4.py  # Make sure to replace with the correct filename
